# Lista 2

### Zaimplementowane biblioteki

In [2]:
import numpy as np
from scipy import linalg

### Funkcje używane w zadaniach

In [4]:
def partial_elimination(A,b):
    A = np.array(A).astype(float)
    b = np.array(b).astype(float)
    n = len(b)
    row_idx = 0
    col_idx = 0
    for i in range(n-1):
        col_nums = []
        col_nums.append(A[row_idx:,i])
        col_max = np.max(col_nums)
        pivot_row = np.argwhere(A[:,col_idx]==col_max)[-1][0]
        A[[row_idx, pivot_row]] = A[[pivot_row, row_idx]]
        b[[row_idx, pivot_row]] = b[[pivot_row, row_idx]]
        for k in range(row_idx, n-1):
            lam = A[k+1,col_idx]/A[row_idx,col_idx]
            A[k+1, :] = A[k+1, :] - lam*A[row_idx, :]
            b[k+1] = b[k+1] - lam*b[row_idx]
        row_idx += 1
        col_idx += 1  
    for k in range(n-1,-1,-1):
        b[k] = (b[k] - np.dot(A[k,k+ 1:n],b[k+ 1:n]))/A[k,k] 
    return A, b     

### Zadanie 4

In [4]:
a = np.array([[0,0,2,1,2],[0,1,0,2,-1],[1,2,0,-2,0],[0,0,0,-1,1],[0,1,-1,1,-1]])
b = np.array([1,1,-4,-2,-1])

_, sol = partial_elimination(a,b)
print(sol)
print(linalg.solve(a,b))

[ 2. -2.  1.  1. -1.]
[ 2. -2.  1.  1. -1.]


### Zadanie 5

In [5]:
a = np.array([[1.0,0.0,0.0,0.0,0.0],[1.0,1.0,1.0,1.0,1.0],[1.0,3.0,9.0,27.0,81.0],[1.0,5.0,5.0**2,5.0**3,5.0**4],[1.0,6.0,6.0**2,6.0**3,6.0**4]])
b = np.array([-1.0,1.0,3.0,2.0,-2.0])

_,sol = partial_elimination(a,b)
print(sol)
print(linalg.solve(a,b))

[-1.          2.68333333 -0.875       0.21666667 -0.025     ]
[-1.          2.68333333 -0.875       0.21666667 -0.025     ]


### Zadanie 6

In [5]:
a = np.array([[3.50,2.77,-0.76,1.80],[-1.80,2.68,3.44,-0.09],[0.27,5.07,6.90,1.61],[1.71,5.45,2.68,1.71]])
b = np.array([7.31,4.23,13.85,11.55])

_,sol = partial_elimination(a,b)
print(sol)
print(linalg.solve(a,b))
print(f'Wyznacznik macierzy A wynosi {np.linalg.det(a)}')
Ax = np.matmul(a, sol)
print(Ax)

[1. 1. 1. 1.]
[1. 1. 1. 1.]
Wyznacznik macierzy A wynosi -0.2257973399999901
[ 7.31  4.23 13.85 11.55]


### Zadanie 7

In [7]:
a = np.array([[10.0,-2.0,-1.0,2.0,3.0,1.0,-4.0,7.0],[5.0,11.0,3.0,10.0,-3.0,3.0,3.0,-4.0],[7.0,12.0,1.0,5.0,3.0,-12.0,2.0,3.0],[8.0,7.0,-2.0,1.0,3.0,2.0,2.0,4.0],[2.0,-15.0,-1.0,1.0,4.0,-1.0,8.0,3.0],[4.0,2.0,9.0,1.0,12.0,-1.0,4.0,1.0],[-1.0,4.0,-7.0,-1.0,1.0,1.0,-1.0,-3.0],[-1.0,3.0,4.0,1.0,3.0,-4.0,7.0,6.0]])
b = np.array([0.0,12.0,-5.0,3.0,-25.0,-26.0,9.0,-7.0])

_,sol = partial_elimination(a,b)
print(sol)
print(linalg.solve(a,b))

[-1.  1. -1.  1. -1.  1. -1.  1.]
[-1.  1. -1.  1. -1.  1. -1.  1.]


### Zadanie 8

In [8]:
a = np.array([[2.0,-1.0,0.0,0.0,0.0,0.0],[-1.0,2.0,-1.0,0.0,0.0,0.0],[0.0,-1.0,2.0,-1.0,0.0,0.0,],[0.0,0.0,-1.0,2.0,-1.0,0.0],[0.0,0.0,0.0,-1.0,-2.0,-1.0,],[0.0,0.0,0.0,0.0,-1.0,5.0]])
b = np.array([[1.0,0.0,0.0,0.0,0.0,0.0],[0.0,1.0,0.0,0.0,0.0,0.0],[0.0,0.0,1.0,0.0,0.0,0.0],[0.0,0.0,0.0,1.0,0.0,0.0],[0.0,0.0,0.0,0.0,1.0,0.0],[0.0,0.0,0.0,0.0,0.0,1.0]])

_,sol = partial_elimination(a,b)
print(sol)
print(linalg.inv(a))
print(f'Macierz odwrotna nie jest trójdiagonalna')

[[ 0.78666667  0.57333333  0.36        0.14666667 -0.06666667 -0.01333333]
 [ 0.57333333  1.14666667  0.72        0.29333333 -0.13333333 -0.02666667]
 [ 0.36        0.72        1.08        0.44       -0.2        -0.04      ]
 [ 0.14666667  0.29333333  0.44        0.58666667 -0.26666667 -0.05333333]
 [-0.06666667 -0.13333333 -0.2        -0.26666667 -0.33333333 -0.06666667]
 [-0.01333333 -0.02666667 -0.04       -0.05333333 -0.06666667  0.18666667]]
[[ 0.78666667  0.57333333  0.36        0.14666667 -0.06666667 -0.01333333]
 [ 0.57333333  1.14666667  0.72        0.29333333 -0.13333333 -0.02666667]
 [ 0.36        0.72        1.08        0.44       -0.2        -0.04      ]
 [ 0.14666667  0.29333333  0.44        0.58666667 -0.26666667 -0.05333333]
 [-0.06666667 -0.13333333 -0.2        -0.26666667 -0.33333333 -0.06666667]
 [-0.01333333 -0.02666667 -0.04       -0.05333333 -0.06666667  0.18666667]]
Macierz odwrotna nie jest trójdiagonalna


### Zadanie 9

In [9]:
a = np.array([[1.0,3.0,-9.0,6.0,4.0],[2.0,-1.0,6.0,7.0,1.0],[3.0,2.0,-3.0,15.0,5.0],[8.0,-1.0,1.0,4.0,2.0],[11.0,1.0,-2.0,18.0,7.0]])
b = np.array([[1.0,0.0,0.0,0.0,0.0],[0.0,1.0,0.0,0.0,0.0],[0.0,0.0,1.0,0.0,0.0],[0.0,0.0,0.0,1.0,0.0],[0.0,0.0,0.0,0.0,1.0]])

arr, sol = partial_elimination(a,b)
print(sol)
print(arr)
print(f'Wyznacznik macierzy A jest równy {linalg.det(a)} więc macierz odwrotna nie istnieje')

[[-7.42166231e+14 -7.42166231e+14 -7.42166231e+14 -1.48433246e+15
   1.48433246e+15]
 [-3.52528960e+15 -3.52528960e+15 -3.52528960e+15 -7.05057919e+15
   7.05057919e+15]
 [-5.90359502e+14 -5.90359502e+14 -5.90359502e+14 -1.18071900e+15
   1.18071900e+15]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  1.00000000e+00
  -1.00000000e+00]
 [ 1.50119988e+15  1.50119988e+15  1.50119988e+15  3.00239975e+15
  -3.00239975e+15]]
[[ 1.10000000e+01  1.00000000e+00 -2.00000000e+00  1.80000000e+01
   7.00000000e+00]
 [ 0.00000000e+00  2.90909091e+00 -8.81818182e+00  4.36363636e+00
   3.36363636e+00]
 [ 0.00000000e+00  0.00000000e+00  2.78125000e+00  7.50000000e+00
   1.09375000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   6.66133815e-16]]
Wyznacznik macierzy A jest równy 0.0 więc macierz odwrotna nie istnieje
